sudo: false
language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - npm install
  - npm run-script test-no-upload
