sudo: false
language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - npm install
  - npm run-script test-no-upload

# encrpyt channel name to get around issue
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      # encrpyted string was "irc.mozilla.org#taskcluster-bots"
      - secure: "dNCICPvkptxnAGZI0vO9zFZ17C5MCEvBQqWOG3q6z5FCM8swHQMF3ZTHk4T+VDFQ9MY8vPDo3e2EhrrWsINmAASmV/cDvGQxQrSf5kmKXjdkhwtOnYmRiwTzTPubYMjRjNEyaLPAQF68rThlMbLauTvbf5poYsjU7UCdtR5juwg="
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
